const a = {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: '/6UkfOZRPQdMt3Vwt0Zb5bnZUyvh.jpg',
      id: 804150,
      title: 'Cocaine Bear',
      original_language: 'en',
      original_title: 'Cocaine Bear',
      overview:
        'Inspired by a true story, an oddball group of cops, criminals, tourists and teens converge in a Georgia forest where a 500-pound black bear goes on a murderous rampage after unintentionally ingesting cocaine.',
      poster_path: '/gOnmaxHo0412UVr1QM5Nekv1xPi.jpg',
      media_type: 'movie',
      genre_ids: [53, 35],
      popularity: 258.402,
      release_date: '2023-02-22',
      video: false,
      vote_average: 7.0,
      vote_count: 122,
    },
    {
      adult: false,
      backdrop_path: '/tt79dbOPd9Z9ykEOpvckttgYXwH.jpg',
      id: 545611,
      title: 'Everything Everywhere All at Once',
      original_language: 'en',
      original_title: 'Everything Everywhere All at Once',
      overview:
        "An aging Chinese immigrant is swept up in an insane adventure, where she alone can save what's important to her by connecting with the lives she could have led in other universes.",
      poster_path: '/rKvCys0fMIIi1X9rmJBxTPLAtoU.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 878],
      popularity: 1039.668,
      release_date: '2022-03-24',
      video: false,
      vote_average: 7.949,
      vote_count: 3712,
    },
    {
      adult: false,
      backdrop_path: '/eN6R6mb3ntHwA3y3MhSwpP78ljN.jpg',
      id: 722149,
      title: 'Luther: The Fallen Sun',
      original_language: 'en',
      original_title: 'Luther: The Fallen Sun',
      overview:
        'A gruesome serial killer is terrorizing London while brilliant but disgraced detective John Luther sits behind bars. Haunted by his failure to capture the cyber psychopath who now taunts him, Luther decides to break out of prison to finish the job by any means necessary.',
      poster_path: '/xsW7M4b4gawgFKCzcXHL2MSeswj.jpg',
      media_type: 'movie',
      genre_ids: [53, 80, 28, 18],
      popularity: 189.448,
      release_date: '2023-02-24',
      video: false,
      vote_average: 6.984,
      vote_count: 190,
    },
    {
      adult: false,
      backdrop_path: '/wybmSmviUXxlBmX44gtpow5Y9TB.jpg',
      id: 594767,
      title: 'Shazam! Fury of the Gods',
      original_language: 'en',
      original_title: 'Shazam! Fury of the Gods',
      overview:
        'Billy Batson and his foster siblings, who transform into superheroes by saying "Shazam!", are forced to get back into action and fight the Daughters of Atlas, who they must stop from using a weapon that could destroy the world.',
      poster_path: '/zpCCTtuQMHiHycpsrWnW2eCrBql.jpg',
      media_type: 'movie',
      genre_ids: [28, 35, 14, 878],
      popularity: 509.522,
      release_date: '2023-03-15',
      video: false,
      vote_average: 7.625,
      vote_count: 8,
    },
    {
      adult: false,
      backdrop_path: '/ae4xZiU7IeFVrvXxm2GjdcTrBm.jpg',
      id: 934433,
      title: 'Scream VI',
      original_language: 'en',
      original_title: 'Scream VI',
      overview:
        'Following the latest Ghostface killings, the four survivors leave Woodsboro behind and start a fresh chapter.',
      poster_path: '/aePBN8ffLCHoUXp8lkA5P29CXdx.jpg',
      media_type: 'movie',
      genre_ids: [27, 9648, 53],
      popularity: 966.423,
      release_date: '2023-03-08',
      video: false,
      vote_average: 7.485,
      vote_count: 230,
    },
    {
      adult: false,
      backdrop_path: '/r7Dfg9aRZ78gJsmDlCirIIlNH3d.jpg',
      id: 785084,
      title: 'The Whale',
      original_language: 'en',
      original_title: 'The Whale',
      overview:
        'A reclusive English teacher suffering from severe obesity attempts to reconnect with his estranged teenage daughter for one last chance at redemption.',
      poster_path: '/jQ0gylJMxWSL490sy0RrPj1Lj7e.jpg',
      media_type: 'movie',
      genre_ids: [18],
      popularity: 1951.845,
      release_date: '2022-12-09',
      video: false,
      vote_average: 8.044,
      vote_count: 1209,
    },
    {
      adult: false,
      backdrop_path: '/6ZZjNFjTlO9F25467CruIibwuxl.jpg',
      id: 739405,
      title: 'Operation Fortune: Ruse de Guerre',
      original_language: 'en',
      original_title: 'Operation Fortune: Ruse de Guerre',
      overview:
        "Special agent Orson Fortune and his team of operatives recruit one of Hollywood's biggest movie stars to help them on an undercover mission when the sale of a deadly new weapons technology threatens to disrupt the world order.",
      poster_path: '/vQGw9lzfh9hEoYSOWAE5XbZ6J7s.jpg',
      media_type: 'movie',
      genre_ids: [28, 53, 35],
      popularity: 333.883,
      release_date: '2023-01-04',
      video: false,
      vote_average: 6.78,
      vote_count: 168,
    },
    {
      adult: false,
      backdrop_path: '/wpYIojB9rTOUMTPmlbikejVZEZT.jpg',
      id: 1087040,
      title: 'Money Shot: The Pornhub Story',
      original_language: 'en',
      original_title: 'Money Shot: The Pornhub Story',
      overview:
        'Featuring interviews with performers, activists and past employees, this documentary offers a deep dive into the successes and scandals of Pornhub.',
      poster_path: '/g7fD1EHgctNSjBUzAOfxEsHaB2k.jpg',
      media_type: 'movie',
      genre_ids: [99],
      popularity: 90.705,
      release_date: '2023-03-15',
      video: false,
      vote_average: 6.4,
      vote_count: 7,
    },
    {
      adult: false,
      backdrop_path: '/v2LilmCylr3bL9TCZSj6syjowZh.jpg',
      id: 937278,
      title: 'A Man Called Otto',
      original_language: 'en',
      original_title: 'A Man Called Otto',
      overview:
        'When a lively young family moves in next door, grumpy widower Otto Anderson meets his match in a quick-witted, pregnant woman named Marisol, leading to an unlikely friendship that turns his world upside down.',
      poster_path: '/130H1gap9lFfiTF9iDrqNIkFvC9.jpg',
      media_type: 'movie',
      genre_ids: [35, 18],
      popularity: 842.437,
      release_date: '2022-12-28',
      video: false,
      vote_average: 7.888,
      vote_count: 732,
    },
    {
      adult: false,
      backdrop_path: '/e8BCc8Jk11dnSffI6ElICLePvLZ.jpg',
      id: 603692,
      title: 'John Wick: Chapter 4',
      original_language: 'en',
      original_title: 'John Wick: Chapter 4',
      overview:
        'With the price on his head ever increasing, John Wick uncovers a path to defeating The High Table. But before he can earn his freedom, Wick must face off against a new enemy with powerful alliances across the globe and forces that turn old friends into foes.',
      poster_path: '/vZloFAK7NmvMGKE7VkF5UHaz0I.jpg',
      media_type: 'movie',
      genre_ids: [28, 53, 80],
      popularity: 342.683,
      release_date: '2023-03-22',
      video: false,
      vote_average: 9.2,
      vote_count: 6,
    },
    {
      adult: false,
      backdrop_path: '/ovM06PdF3M8wvKb06i4sjW3xoww.jpg',
      id: 76600,
      title: 'Avatar: The Way of Water',
      original_language: 'en',
      original_title: 'Avatar: The Way of Water',
      overview:
        'Set more than a decade after the events of the first film, learn the story of the Sully family (Jake, Neytiri, and their kids), the trouble that follows them, the lengths they go to keep each other safe, the battles they fight to stay alive, and the tragedies they endure.',
      poster_path: '/t6HIqrRAclMCA60NsSmeqe9RmNV.jpg',
      media_type: 'movie',
      genre_ids: [878, 12, 28],
      popularity: 1104.179,
      release_date: '2022-12-14',
      video: false,
      vote_average: 7.73,
      vote_count: 5748,
    },
    {
      adult: false,
      backdrop_path: '/mqsPyyeDCBAghXyjbw4TfEYwljw.jpg',
      id: 49046,
      title: 'All Quiet on the Western Front',
      original_language: 'de',
      original_title: 'Im Westen nichts Neues',
      overview:
        'Paul Baumer and his friends Albert and Muller, egged on by romantic dreams of heroism, voluntarily enlist in the German army. Full of excitement and patriotic fervour, the boys enthusiastically march into a war they believe in. But once on the Western Front, they discover the soul-destroying horror of World War I.',
      poster_path: '/hYqOjJ7Gh1fbqXrxlIao1g8ZehF.jpg',
      media_type: 'movie',
      genre_ids: [18, 10752, 36],
      popularity: 633.69,
      release_date: '2022-10-07',
      video: false,
      vote_average: 7.759,
      vote_count: 2217,
    },
    {
      adult: false,
      backdrop_path: '/A5JyEZvXHbPLN2cU65oB9NaIuYH.jpg',
      id: 768362,
      title: 'Missing',
      original_language: 'en',
      original_title: 'Missing',
      overview:
        'When her mother disappears while on vacation in Colombia with her new boyfriend, June’s search for answers is hindered by international red tape. Stuck thousands of miles away in Los Angeles, June creatively uses all the latest technology at her fingertips to try and find her before it’s too late. But as she digs deeper, her digital sleuthing raises more questions than answers... and when June unravels secrets about her mom, she discovers that she never really knew her at all.',
      poster_path: '/jYXJW19PMEUrpyavEHrnnlItQn1.jpg',
      media_type: 'movie',
      genre_ids: [18, 9648, 53],
      popularity: 159.421,
      release_date: '2023-01-19',
      video: false,
      vote_average: 7.7,
      vote_count: 150,
    },
    {
      adult: false,
      backdrop_path: '/5i6SjyDbDWqyun8klUuCxrlFbyw.jpg',
      id: 677179,
      title: 'Creed III',
      original_language: 'en',
      original_title: 'Creed III',
      overview:
        'After dominating the boxing world, Adonis Creed has been thriving in both his career and family life. When a childhood friend and former boxing prodigy, Damien Anderson, resurfaces after serving a long sentence in prison, he is eager to prove that he deserves his shot in the ring. The face-off between former friends is more than just a fight. To settle the score, Adonis must put his future on the line to battle Damien - a fighter who has nothing to lose.',
      poster_path: '/vJU3rXSP9hwUuLeq8IpfsJShLOk.jpg',
      media_type: 'movie',
      genre_ids: [18],
      popularity: 1218.53,
      release_date: '2023-03-01',
      video: false,
      vote_average: 7.0,
      vote_count: 336,
    },
    {
      adult: false,
      backdrop_path: '/bQTfSXQrcVwXJ5TvNzbd3ioMnnM.jpg',
      id: 862552,
      title: 'The Ritual Killer',
      original_language: 'en',
      original_title: 'The Ritual Killer',
      overview:
        'Unable to process the death of his daughter, Detective Boyd embarks on a hunt for a serial killer who murders according to a brutal tribal ritual: Muti. The only person who can help Boyd is Professor Mackles, an anthropologist who hides an unspeakable secret. The line between sanity and madness thins as Boyd goes deeper into the killer’s world.',
      poster_path: '/1VtHaELqLMovl8EueBWHDtihhzF.jpg',
      media_type: 'movie',
      genre_ids: [28, 53],
      popularity: 121.556,
      release_date: '2023-03-10',
      video: false,
      vote_average: 5.9,
      vote_count: 18,
    },
    {
      adult: false,
      backdrop_path: '/8H2O044M0xp240emFWAXjZsfLLx.jpg',
      id: 700391,
      title: '65',
      original_language: 'en',
      original_title: '65',
      overview:
        "After a catastrophic crash on an unknown planet, pilot Mills quickly discovers he's actually stranded on Earth…65 million years ago. Now, with only one chance at rescue, Mills and the only other survivor, Koa, must make their way across an unknown terrain riddled with dangerous prehistoric creatures in an epic fight to survive.",
      poster_path: '/uMMIeMVk1TCG3CZilpxbzFh0JKT.jpg',
      media_type: 'movie',
      genre_ids: [53, 878, 28],
      popularity: 392.443,
      release_date: '2023-03-02',
      video: false,
      vote_average: 5.973,
      vote_count: 55,
    },
    {
      adult: false,
      backdrop_path: '/dlrWhn0G3AtxYUx2D9P2bmzcsvF.jpg',
      id: 536554,
      title: 'M3GAN',
      original_language: 'en',
      original_title: 'M3GAN',
      overview:
        "A brilliant toy company roboticist uses artificial intelligence to develop M3GAN, a life-like doll programmed to emotionally bond with her newly orphaned niece. But when the doll's programming works too well, she becomes overprotective of her new friend with terrifying results.",
      poster_path: '/d9nBoowhjiiYc4FBNtQkPY7c11H.jpg',
      media_type: 'movie',
      genre_ids: [878, 27, 35],
      popularity: 893.412,
      release_date: '2022-12-28',
      video: false,
      vote_average: 7.435,
      vote_count: 2044,
    },
    {
      adult: false,
      backdrop_path: '/xDMIl84Qo5Tsu62c9DGWhmPI67A.jpg',
      id: 505642,
      title: 'Black Panther: Wakanda Forever',
      original_language: 'en',
      original_title: 'Black Panther: Wakanda Forever',
      overview:
        'Queen Ramonda, Shuri, M’Baku, Okoye and the Dora Milaje fight to protect their nation from intervening world powers in the wake of King T’Challa’s death.  As the Wakandans strive to embrace their next chapter, the heroes must band together with the help of War Dog Nakia and Everett Ross and forge a new path for the kingdom of Wakanda.',
      poster_path: '/sv1xJUazXeYqALzczSZ3O6nkH75.jpg',
      media_type: 'movie',
      genre_ids: [28, 12, 878],
      popularity: 1947.255,
      release_date: '2022-11-09',
      video: false,
      vote_average: 7.335,
      vote_count: 4095,
    },
    {
      adult: false,
      backdrop_path: '/4eC0tsU9OxR3Adlo1yRJYUDraW9.jpg',
      id: 1092899,
      title: 'The Siege',
      original_language: 'en',
      original_title: 'The Siege',
      overview:
        'International assassin Walker is compromised during a mission and sent to a reassignment center for a new identity. During his stay at the facility, a ruthless assault team storms the compound searching for someone their boss has lost. Walker begrudgingly falls in with skilled hitwoman Elda and her mysterious ward Juliet in order to survive the night.',
      poster_path: '/hVh4hMzkXNLnScudbid6hDvjMPk.jpg',
      media_type: 'movie',
      genre_ids: [28, 53],
      popularity: 16.724,
      release_date: '2023-03-10',
      video: false,
      vote_average: 5.5,
      vote_count: 6,
    },
    {
      adult: false,
      backdrop_path: '/jr8tSoJGj33XLgFBy6lmZhpGQNu.jpg',
      id: 315162,
      title: 'Puss in Boots: The Last Wish',
      original_language: 'en',
      original_title: 'Puss in Boots: The Last Wish',
      overview:
        'Puss in Boots discovers that his passion for adventure has taken its toll: He has burned through eight of his nine lives, leaving him with only one life left. Puss sets out on an epic journey to find the mythical Last Wish and restore his nine lives.',
      poster_path: '/kuf6dutpsT0vSVehic3EZIqkOBt.jpg',
      media_type: 'movie',
      genre_ids: [16, 12, 35, 10751],
      popularity: 2176.668,
      release_date: '2022-12-07',
      video: false,
      vote_average: 8.363,
      vote_count: 4608,
    },
  ],
  total_pages: 1000,
  total_results: 20000,
};
